---
- name: Copy jar file to inventory i.e. Pull docker image
  hosts: all
  tasks:
    - name: Pull junit devops image
      docker_image:
        name: manas2024/calculator
        source: pull
#    - name: Running Docker Img
#          run: docker run -it -d manas2024/calculator
